apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # 這是minikube的storage cluster 請確認部署的k8s環境的storage class 在進行修改
